### ISSUE TITLE
search-buffers exits/hangs unexpectedly

### ISSUE THREAD

**Issue by wxie2017** [atlas-engineer/next#590] opened 2020-03-07 01:37 UTC
**Describe the bug**
search buffers using search-buffers function cause NEXT to exit

**Precise recipe to reproduce the issue**
1. open NEXT by ./next or (next:start)
2. M-x search buffers
3. select 3 or more buffers using C-space
4. input search strings such as "run" or "next"
5. if NEXT was started as ./next, it exits often
6. if NEXT was started as (next:start), it hangs with information "sbcl is not repsonding"

**Information**
    OS name+version: Linux kali 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux
    Kernel name+version: 5.4.0-kali3-amd64
    Graphics card and driver: 00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])
    Subsystem: Lenovo 3rd Gen Core processor Graphics Controller [17aa:3800]
    Flags: bus master, fast devsel, latency 0, IRQ 29
    Memory at d8000000 (64-bit, non-prefetchable) [size=4M]
    Memory at c0000000 (64-bit, prefetchable) [size=256M]
    I/O ports at 4000 [size=64]
    Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
    Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
    Capabilities: [d0] Power Management version 2
    Capabilities: [a4] PCI Advanced Features
    Kernel driver in use: i915
    Kernel modules: i915
    Desktop environment / Window manager name+version: gdm3, GDM 3.34.1
    Next version (from =M-x next-version= or =next --version=): Next 1.5.0-090e5a1
    How you installed Next (Guix pack, package manager, build from source): build from source
    SBCL version (if built from source): SBCL 2.0.1.debian
    WebKitGTK+ / PyQt-Webengine version: libwebkit2-sharp-4.0-cil-dev/kali-rolling 2.10.9+git20160917-1.1 amd64
    CLI bindings for WebKitGTK+ 4.0 using GObject Introspection - development

console information:
  "Finished loading: https://next.atlas.engineer/documentation#jumping-to-headings."
 <INFO> [09:09:52] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://next.atlas.engineer/documentation."
 <INFO> [09:09:52] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://next.atlas.engineer/documentation#navigation."
 <INFO> [09:09:52] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://next.atlas.engineer/feed."
 <INFO> [09:09:53] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://next.atlas.engineer/documentation#customization."
 <INFO> [09:09:54] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://next.atlas.engineer/documentation."
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                  {10069D41F3}>:
  The value
    NIL
  is not of type
    STRING
  when binding STRING

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10069D41F3}>
0: (MAKE-STRING-INPUT-STREAM NIL 70026941333600 T) [external]
1: (JSON:DECODE-JSON-FROM-STRING NIL)
2: (NEXT::MATCHES-FROM-JSON NIL #<NEXT:GTK-BUFFER {1006A44433}> T)
3: ((LAMBDA (NEXT::RESULT) :IN NEXT::MATCH-COMPLETION-FUNCTION) NIL)
4: ((LAMBDA (CL-WEBKIT2::SOURCE-OBJECT CL-WEBKIT2::RESULT CL-WEBKIT2::USER-DATA) :IN "/root/common-lisp/next/quicklisp/local-projects/cl-webkit/webkit2/webkit2.web-view.lisp") #<unused argument> #.(SB-SYS:INT-SAP #X7F60680086C0) #.(SB-SYS:INT-SAP #X00000052))
5: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/root/common-lisp/next/quicklisp/dists/quicklisp/software/cl-cffi-gtk-20190710-git/gdk/gdk.seat.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
6: ("foreign function: funcall_alien_callback")
7: ("foreign function: callback_wrapper_trampoline")
8: ("foreign function: #x50101BDC")
9: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
13: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
15: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {7F60D5ECED7B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10069D41F3}>> NIL T NIL)
16: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {10069D41F3}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {10069D419B}> NIL)
17: ("foreign function: call_into_lisp")
18: ("foreign function: new_thread_trampoline")

 <INFO> [09:13:38] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://next.atlas.engineer/documentation#navigation."
Could not evaluate JavaScript: GError: Domain: "WebKitJavascriptError", Code: 699, Message: about:blank:1:32: TypeError: null is not an object (evaluating 'document.getElementById('head').scrollIntoView')
 <INFO> [09:13:40] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://next.atlas.engineer/documentation."
 <INFO> [09:13:40] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://next.atlas.engineer/feed."
 <INFO> [09:13:40] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://next.atlas.engineer/documentation#visiting-urls."
 <INFO> [09:13:41] next minibuffer.lisp (echo form-fun-6) -
  "Loading: https://next.atlas.engineer/feed."
 <INFO> [09:13:42] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://github.com/atlas-engineer/next."
 <INFO> [09:13:43] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://github.com/."
 <INFO> [09:13:45] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://next.atlas.engineer/documentation."
 <INFO> [09:13:48] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://next.atlas.engineer/feed."
 <INFO> [09:13:49] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://github.com/atlas-engineer/next."
 <INFO> [09:14:00] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://github.com/atlas-engineer/next."
 <INFO> [09:14:01] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://github.com/atlas-engineer/next."
 <INFO> [09:14:03] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://github.com/atlas-engineer/next."
 <INFO> [09:14:15] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://next.atlas.engineer/feed."
 <INFO> [09:15:35] next minibuffer.lisp (echo form-fun-6) -
  "Finished loading: https://github.com/explore."

If you need more information, please let me know.

**Comment by jmercouris** [comment] 2020-03-07 14:39
I cannot reproduce this behavior. Can please provide an example of 3 URLs together which cause this problem?

**Comment by wxie2017** [comment] 2020-03-08 01:30
Next  https://next.atlas.engineer/documentation
https://next.atlas.engineer/feed
Next  https://next.atlas.engineer/documentation#customization
Next  https://next.atlas.engineer/documentation#jumping-to-headings
Next  https://next.atlas.engineer/documentation#customization
Next  https://next.atlas.engineer/documentation#jumping-to-headings

This link causes problem:
https://next.atlas.engineer/feed

By the way, how to copy the selected links? M-w is not working.

**Comment by jmercouris** [comment] 2020-03-08 12:36
When using highlighted text you can use C-c to copy and C-v to paste

**Comment by Ambrevar** [comment] 2020-03-09 17:38
This should be fixed with c405defd89bc2c073c15c3cc98a7dccf97b6274e.  Can
you retry on master?

Next still crashes quite frequently but we are slowly getting there :)

**Comment by wxie2017** [comment] 2020-03-10 13:36
Next 1.5.0-fcb313c is not ok: search-buffers still crashes when input.

**Comment by Ambrevar** [comment] 2020-03-10 13:43
What's the WebKitGTK version (as per reported by your package manager --
it's not "4.0").

**Comment by wxie2017** [comment] 2020-03-10 15:00
How could I find out my WebKitGTK+ / PyQt-Webengine version?

**Comment by Ambrevar** [comment] 2020-03-10 15:49
I think `apt show webkitgtk` in a shell should do it.

**Comment by wxie2017** [comment] 2020-03-10 23:12
~/common-lisp/next # apt show WebKitGTK+
Package: libwebkitgtk-1.0-0
State: not a real package (virtual)
Package: libwebkitgtk-3.0-0
State: not a real package (virtual)
N: No packages found

I cannot find 4.0.

**Comment by Ambrevar** [comment] 2020-03-11 07:56
Maybe `apt search webkitgtk` then?

**Comment by wxie2017** [comment] 2020-03-11 12:19
~/common-lisp/next # apt search WebKitGTK+
Sorting... Done
Full Text Search... Done
epiphany-browser/kali-rolling 3.34.1-1+b1 amd64
  Intuitive GNOME web browser

gir1.2-javascriptcoregtk-4.0/kali-rolling,now 2.26.4-1 amd64 [installed,automatic]
  JavaScript engine library from WebKitGTK - GObject introspection data

libjavascriptcoregtk-4.0-18/kali-rolling,now 2.26.4-1 amd64 [installed,automatic]
  JavaScript engine library from WebKitGTK

libjavascriptcoregtk-4.0-bin/kali-rolling 2.26.4-1 amd64
  JavaScript engine library from WebKitGTK - command-line interpreter

libjavascriptcoregtk-4.0-dev/kali-rolling,now 2.26.4-1 amd64 [installed,automatic]
  JavaScript engine library from WebKitGTK - development files

libwebkit2-sharp-4.0-cil/kali-rolling 2.10.9+git20160917-1.1 amd64
  CLI bindings for WebKitGTK+ 4.0 using GObject Introspection

libwebkit2-sharp-4.0-cil-dev/kali-rolling 2.10.9+git20160917-1.1 amd64
  CLI bindings for WebKitGTK+ 4.0 using GObject Introspection - development

libwebkit2gtk-4.0-37-gtk2/kali-rolling 2.26.4-1 all
  Transitional dummy package

luakit/kali-rolling 1:2.1-2 amd64
  fast and small web browser extensible by Lua

ruby-webkit2-gtk/kali-rolling 3.4.1-2 all
  WebKitGTK+ bindings for the Ruby language

webkit2gtk-driver/kali-rolling 2.26.4-1 amd64
  WebKitGTK WebDriver support

**Comment by Ambrevar** [comment] 2020-03-12 08:16
Are you getting hit by this consistently?
There might be a race condition and my CPU being faster or slower than
yours would explain why I'm not seeing this.

Either way, I think the proper fix to this with the new architecture is
to catch conditions for all Parenscript code.

**Comment by wxie2017** [comment] 2020-03-12 14:05
It happens very often and I can easily reproduce.
What's your nick for IRC?

**Comment by Ambrevar** [comment] 2020-03-12 14:15
I'm not on IRC, sorry.

**Comment by Ambrevar** [comment] 2020-04-10 13:54
Should be fixed with 0ae04b2c8272c46fb609362f6cea65df912a356a.

**Closed** 2020-04-17 14:04 UTC
Labels: 2.0
