### ISSUE TITLE
Space Bar Doesn't Work in Text Entry Boxes

### ISSUE THREAD

**Issue by dylanjm** [atlas-engineer/next#305] opened 2019-08-11 07:28 UTC
Hello, new user and really excited to continue trying this out. I saw a previous issue that said a home-brew cask was now available for Next, so I gave it a try this evening. I'm currently running macOS Mojave 10.14.6. 

I installed Next via:

```
brew cask install next
```

When I open the url to youtube, the text entry box is automatically selected, but I can't use the spacebar or hit enter. This behavior is the same when using google.com search bar.

**Comment by vindarel** [comment] 2019-08-11 14:06
Hello, thanks for the report. The homebrew recipe is not official, so it would be helpful if you compared with the build available in MacPorts, or if you built from sources.

**Comment by jmercouris** [comment] 2019-08-11 16:25
The problem is due to changes we made in key handling to make it work on both macOS and Linux, I suggest we make OS specific versions of the function to resolve the issue

**Comment by Ambrevar** [comment] 2019-08-11 17:56
Which function?

**Comment by jmercouris** [comment] 2019-08-11 18:39
`create_key_string` in utility.py

**Comment by jmercouris** [comment] 2020-04-20 11:09
fixed on master :-)

**Closed by jmercouris** 2020-04-20 11:09 UTC
Labels: 2.0, homebrew, macos
