### ISSUE TITLE
Next/Gtk keeps closing 

### ISSUE THREAD

**Issue by j3ky** [atlas-engineer/next#97] opened 2018-05-09 14:18 UTC
Hey, I've compile with success the Next binary (next-gtk).

It runs for awhile then it just shutdown with no apparent errror

I get it running from a terminal:

```
S-W-M
S-W-M
S-W-M
S-W-M
S-W-M

(next:18604): Gtk-CRITICAL **: 11:14:48.478: gtk_tree_path_to_string: assertion 'path != NULL' failed

```

**Running Next (next:start) from SBCL wont close as the binary version**

Compilation output:

> [lyr3:~/Temps/next/next] $ make build-gtk

```
sbcl --load next.asd \
        --eval '(ql:quickload :next/gtk)' \
        --eval '(asdf:make :next/gtk)' \
        --eval '(quit)'
This is SBCL 1.4.7.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
To load "next/gtk":
  Load 1 ASDF system:
    next/gtk
; Loading "next/gtk"
..........................
[undoing binding stack and other enclosing state... done]
[performing final GC... done]
[defragmenting immobile space... 1870+35026+2494+4204+29002+33285 objects... done]
[saving current Lisp image into /home/lyr3/Temps/next/next/source/next-gtk:
writing 0 bytes from the read-only space at 0x20000000
writing 6464 bytes from the static space at 0x20100000
writing 69763072 bytes from the dynamic space at 0x1000000000
writing 3108864 bytes from the immobile space at 0x20300000
writing 22528896 bytes from the immobile space at 0x21b00000
done]
```

--------------------
Debian GNU Linux

SBCL 1.4.7.debian

**Comment by jmercouris** [comment] 2018-05-09 14:25
Hi, thank you for your report! Just to clarify,

So you're saying when it runs in the REPL it doesn't crash? but when you run as a standalone it crashes?

**Comment by jmercouris** [comment] 2018-05-09 16:17
Yes, that is very strange. I have no idea why that could be. I'll try to look into, thank you again for the report!

**Comment by jmercouris** [comment] 2018-05-09 20:40
Hi, I really appreciate the offer!

The problem is, that I don't know how to debug a compiled binary. I'm not sure how to get to the restarts (normally used in Lisp). Perhaps asking #lisp on free node can yield some better results...

**Comment by sdilts** [comment] 2018-05-09 21:25
I'm having the same problem, execept the linux binary immediately closses with no output

**Comment by lyr3** [comment] 2018-05-09 23:56
@jmercouris 
Ok!

**Comment by Ambrevar** [comment] 2018-05-19 18:09
I can reproduce on Guix.

**Comment by Ambrevar** [comment] 2018-05-19 23:01
Found out something: it seems that the compiled version always shuts down after precisely 60 seconds!

@jmercouris Are you using some timers? Any clue what that could be?
@lyr3 Can you confirm?

**Comment by cybem** [comment] 2018-05-20 07:01
Same for me. Compiled version crashes. Ubuntu 18.04, SBCL 1.4.7, amd64. But it works from REPL.

**Comment by Ambrevar** [comment] 2018-05-20 07:41
@cybem: Does it crash exactly after 60 seconds?

**Comment by cybem** [comment] 2018-05-20 07:50
It crashes immediately. It starts, prints "S-W-M" several times, opens a window and exits without errors and core dumps. I've tried to find out a reason using strace recently but it didn't bring any result. Everything seems ok, but it doesn't work :-)

**Comment by Ambrevar** [comment] 2018-05-20 08:41
The end of my strace:

```
sched_getaffinity(6027, 32, [0, 1, 2, 3]) = 32
rt_sigprocmask(SIG_UNBLOCK, [USR1], NULL, 8) = 0
write(21, "\1\0\0\0\0\0\0\0", 8)        = 8
rt_sigprocmask(SIG_BLOCK, [HUP INT QUIT PIPE ALRM TERM CHLD TSTP URG XCPU XFSZ VTALRM PROF WINCH IO], [], 8) = 0
getpid()                                = 6027
tgkill(6027, 6042, SIGPIPE)             = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x10044036a8, FUTEX_WAIT_PRIVATE, 4, {tv_sec=60, tv_nsec=0}GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
) = ? ERESTART_RESTARTBLOCK (Interrupted by signal)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
restart_syscall(<... resuming interrupted futex ...>) = -1 ETIMEDOUT (Connection timed out)
exit_group(0)                           = ?
+++ exited with 0 +++
```

The

```
 = -1 ETIMEDOUT (Connection timed out)
exit_group(0)                           = ?
```
is output when it terminates (it does not crash actually).  What's yours?

**Comment by Ambrevar** [comment] 2018-05-20 14:16
Progress!
If I start with
```
	$(LISP) \
		--eval '(ql:quickload :cffi)' \
		--eval '(push (format nil "~a/.guix-profile/lib/" (uiop:getenv "HOME")) cffi:*foreign-library-directories*)' \
		--load next.asd \
		--eval '(ql:quickload :next/gtk)' \
		--eval '(next:start)' \
		--eval '(quit)'
```
(Don't mind the 2 cffi lines, it's for Guix only)
Then it closes after 60 seconds.
If I remove the `(quit)` call, then it does not terminates by itself.

Removing the `(quit)` call from `build-gtk` in the Makefile, it does not fix the issue however.
But I suspect the termination to be implicit in because of `asdf:make`.

Also note that the documentation underlines its experimental status:
```
 -- Function: make system &rest keys &key &allow-other-keys
     Do "The Right Thing" with your system.  Starting with ASDF 3.1,
     this function 'make' is also available.  The default behaviour is
     to load the system as if by 'load-system'; but system authors can
     override this default in their system definition they may specify
     an alternate operation as the intended use of their system, with a
     ':build-operation' option in the 'defsystem' form (*note
     build-operation: The defsystem grammar.), and an intended output
     pathname for that operation with ':build-pathname'.  This function
     is experimental and largely untested.  Use at your own risk.
```
@vindarel: Since you worked on the next/gtk, would you have a clue about this?

**Comment by Ambrevar** [comment] 2018-05-20 17:41
Found it!

From the sbcl documentation ((sbcl) Exit):
```
     ‘timeout’ controls waiting for other threads to terminate when
     ‘abort’ is ‘nil’.  Once current thread has been unwound and
     ‘*exit-hooks*’ have been run, spawning new threads is prevented and
     all other threads are terminated by calling ‘terminate-thread’ on
     them.  The system then waits for them to finish using
     ‘join-thread’, waiting at most a total ‘timeout’ seconds for all
     threads to join.  Those threads that do not finish in time are
     simply ignored while the exit protocol continues.  ‘timeout’
     defaults to ‘*exit-timeout*’, which in turn defaults to 60.
     ‘timeout’ ‘nil’ means to wait indefinitely.
```

It's precisely what's happening.  From a quick glance at the code, it seems that Next fires up threads, it seems that sbcl is not waiting for them.

A wordaround is to set
`*exit-timeout*` to `nil` in the binary generation.
As a result closing the Next window won't kill the process automatically.  Not pretty!

A proper fix would be to be to join correctly on the running threads.  @jmercouris?

**Comment by jmercouris** [comment] 2018-05-20 20:02
@Ambrevar 

Thank you for research and debugging! I can only imagine this must be an issue with cl-cffi-gtk, as I am not myself personally spawning any threads. Unless of course I am doing it somewhere in the code and have forgotten. All of the GTK code can be seen in the gtk/ folder.

Once again, thank you for debugging!

**Comment by Ambrevar** [comment] 2018-05-20 20:13
Hmm, can you explain what the following macro is for?
```
(defmacro synchronous-within-main (&body b)
  (let ((promise (gensym "PROMISE"))
	(thunk (gensym "THUNK")))
  `(let ((,thunk (lambda () ,@b)))
     (format *error-output* "S-W-M~%")
     (if (or
	  *within-main-nesting*
	  (string= (bt:thread-name (bt:current-thread))
		   "cl-cffi-gtk main thread"))
	 (funcall ,thunk)
	 (let ((*within-main-nesting* t)
	       (,promise (lparallel:promise)))
	   (gtk:within-main-loop
	     (lparallel:fulfill ,promise
	       (funcall ,thunk)))
	   (lparallel:force ,promise))))))
```

**Comment by jmercouris** [comment] 2018-05-21 10:58
Some operations need to be completed upon the main thread to avoid strange issues within GTK, it made a lot of the code significantly more simple to write.

If you look inside the GTK class, you'll see some places where it is used. It basically ensures that the code nested within that block will run, as the name suggests, synchronously within the main thread.

**Comment by vindarel** [comment] 2018-05-22 14:46
Maybe related: here's how we must join threads when running a webserver from an executable. From this [SO answer](https://stackoverflow.com/questions/30422451/sbcl-deploying-hunchentoot-application-as-executable). Otherwise it exits quickly too.

**Comment by lyr3** [comment] 2018-06-09 12:41
Still...sadly!

**Comment by Ambrevar** [comment] 2018-06-09 20:00
A workaround to build:

```
build-gtk:
	$(LISP) --load next.asd \
		--eval '(ql:quickload :next/gtk)' \
		--eval '(setq *exit-timeout* nil)' \
		--eval '(asdf:make :next/gtk)' \
		--eval '(quit)'
```

I'll working on a proper fix soon.

**Comment by Ambrevar** [comment] 2018-12-02 14:14
This is now fixed on master since the new GTK rewrite.

**Closed by Ambrevar** 2018-12-02 14:14 UTC
