### ISSUE TITLE
DuckDuckGo: Going backward on history returns a weird char "l/"

### ISSUE THREAD

**Issue by lxbarbosa** [atlas-engineer/next#211] opened 2019-05-16 13:23 UTC
Hi,

Searching any term on ddg in a new tab (m-l), visiting any site and going back to that ddg search, now it returns a weird char "l/" instead of "asd"

https://i.ibb.co/jkj9TLq/2019-05-17-010242-1366x768-scrot.png

**Reproduce:**
- m-l (new tab)
- searching for "asd"
- enter any site of that search
- backward on history (c-b)
- returns a ddg page with "l/" 

--------------------------
Next: sbcl-next (guix)
OS: Debian SID 10

**Comment by Ambrevar** [comment] 2019-05-16 13:34
I've experienced this myself.
I'm not sure where that could come from.

@jmercouris any idea?

**Comment by alexanderbarbosa** [comment] 2019-06-13 19:46
@jmercouris @Ambrevar 

I just noticed that the URL as user go backward on history do change, it is not the early DDG search URL :

**ddg search:**  https://duckduckgo.com/?q=meugas+asda&ia=web
**backward history:**  https://duckduckgo.com/l/?kh=-1&uddg=https%3A%2F%2Fgroceries.asda.com%2Fshelf%2Fdining-glassware%2Fsingle-mugs%2F_%2F111421

Maybe DDG do something just before we access a site, like providing an analytic data for websites know that we accessed  their site through DDG.

As Next look for the its parent url, maybe we just need to look for the grand parent url, that I suppose the correct DDG early search url.

**Comment by Ambrevar** [comment] 2019-06-13 20:02
This is what I found as well.
I suspect that we need to check the HTTP return code (probably 200 here)
and decide whether or not to add the URL to the history.

**Comment by Ambrevar** [comment] 2020-04-18 06:54
Could be fixed by #613.

**Comment by jmercouris** [comment] 2020-04-20 15:00
This is fixed! I knew a recipe to reproduce it and it no longer happens :-)

**Comment by Ambrevar** [comment] 2020-04-20 15:37
I can reproduce.  Which recipe did you use?
Mine:

- C-l foo
- Click on the first link.
- M-x history-backwards

Result: it reloads the same page instead of going back to the duckduckgo results.

**Comment by Ambrevar** [comment] 2020-04-20 15:39
I believe this could be fixed if we used WebKitGTK history, which we should for performance reasons.  See #613.

**Comment by jmercouris** [comment] 2020-04-20 15:51
Works for me...

**Comment by jmercouris** [comment] 2020-04-20 15:51
no idea :-D

**Comment by Ambrevar** [comment] 2020-04-25 08:09
Implemented a workaround in dc238e253c39383850573f90f94801484dd16857.

Ideally we would need to use the same strategy as WebKitGTK which is able to skip those redirection URLs automatically.  Maybe look at the response URI status code?

That'll be for another time.

**Closed by Ambrevar** 2020-04-25 08:09 UTC
Labels: 2.0, bug
