### ISSUE TITLE
Arrow keys crash Next (OSX Mojave)

### ISSUE THREAD

**Issue by peterohanley** [atlas-engineer/next#173] opened 2018-12-12 20:00 UTC
Using the arrow keys in the mini buffer crashes next if it's launched from spotlight, but not if it's launched with `open -a next`.
[Crash log](https://gist.github.com/peterohanley/6678cec89cf7da25260fb364048927db)

To reproduce: launch, C-l, hit an arrow key. Launched from spotlight it will crash, from the terminal it will just display a missing character box.

**Comment by jmercouris** [comment] 2018-12-12 20:03
Hi, thank you very much for the report! I think I know what is happening. Because the arrow keys are not mapped in the minibuffer, it'll try to insert them as a character, but that character somehow crashes it in the first instance, but not in the other.

I wonder if it doesn't crash in the second instance you describe because it has standard-out when launched from the terminal. Not sure, I will think about it, thank you!

**Comment by jmercouris** [comment] 2018-12-13 18:51
Just wanted to update you and let you know that I did a little investigation and have figured out what the issue is. Thinking about how to patch it, will get back to you when I have a fix in place! Thank you for your patience!

**Comment by pvinis** [comment] 2019-01-26 12:33
What did you find out in the investigation?

**Comment by pvinis** [comment] 2019-01-26 15:32
Interesting. Looking forward because I'm curious about the solution. This project seems very nice. Also feels very weird for an application to crash but just pressing an arrow, so that made me even more curious about that actual code would be needed.

Thanks for your work and good luck with the project! I will keep trying it and I can't wait for the fix :D

**Comment by peterohanley** [comment] 2019-03-09 21:59
I was curious and it also crashes if you hit the arrow keys just on a webpage.

**Comment by jmercouris** [comment] 2019-03-09 22:08
depends on if the web page frame is in focus or not :)

**Comment by Ambrevar** [comment] 2019-04-19 08:28
@jmercouris : Is this fixed now?

**Comment by jmercouris** [comment] 2019-04-19 10:34
Yes, all good (not fixed in binary yet though, hasn’t been recompiled yet)

**Comment by peterohanley** [comment] 2019-04-20 16:30
I can confirm it doesn't crash. As a bonus, the arrow keys even work!

I'll close this when the release is updated or you can close it now of course.

**Comment by Ambrevar** [comment] 2019-05-08 18:09
This should be fixed in Next 1.2.1. Feel free to re-open if you still experience the issue.

**Closed by Ambrevar** 2019-05-08 18:09 UTC
