### ISSUE TITLE
Can't perform multi-word queries from minibuffer

### ISSUE THREAD

**Issue by 4t0m** [atlas-engineer/next#329] opened 2019-08-20 20:08 UTC
When I use "o"/"O" to perform a search, if my query contains a space then no search is performed.  Instead the minibuffer collapses and displays "VI-NORMAL-MODE enabled."  This happens regardless of whether the first word maps to one of the sites listed in "search-engines".

If I'm in normal mode, then the minibuffer just clears and collapses.

**Comment by Ambrevar** [comment] 2019-08-21 09:24
How did you install next and which version are you running?

There used to be a bug where search engines keyword were not recognized,
but this is now fixed upstream.

**Comment by 4t0m** [comment] 2019-08-21 16:00
I installed using the tar file linked on https://next.atlas.engineer/download and my version number is 1.3.0.

**Comment by Ambrevar** [comment] 2019-08-21 16:25
The issue is fixed upstream.

**Comment by 4t0m** [comment] 2019-08-21 16:40
Oh cool.  I'm currently going through the developer readme and getting my environment set up.  I have some ideas for things to implement, but are there anything you know of already that would be a good first task?  

And if there's a feature I'd like to implement, is the procedure to create an issue to start a discussion on whether it fits the philosophy of the project and how it might be implemented?

**Comment by Ambrevar** [comment] 2019-08-21 16:50
Great to see you interested by the project!

We've got lots of ideas indeed!  Improve link-hinting, improved search,
bookmarks on steroids, etc.
Maybe the latter would be the easiest to get started, as it does not
interfere with the rest and it requires relatively little Common Lisp
knowledge.

Before we overhaul Next' homepage, feel free to start a discussion on
the issue tracker here on GitHub.  All ideas are welcome for discussion!

**Comment by 4t0m** [comment] 2019-08-21 17:03
I would love to work on bookmarks.  I'll comment on the existing issue.

I'm interested in link hinting as well, but it looked like it might be pretty complicated and much more involved with Common Lisp.  I think I saw you recommend some resources for learning Common Lisp on another issue.  Do you have those/any others on hand?

So, I'll close this issue then?

**Closed** 2019-08-21 22:06 UTC

**Comment by Ambrevar** [comment] 2019-08-22 07:31
If you are already familiar with programming in another language, some
resources I recommend to get started with Common Lisp:

- http://www.gigamonkeys.com/book/: Free book, covers the "core" quite
  well, the first 22 chapters can be covered pretty fast.

- https://lispcookbook.github.io/cl-cookbook/: Modern, community
  maintained cookbook covering a lot of aspects from editor setup to
  style.  If you already know another Lisp/Scheme, this can get you
  started real fast.  Also very convenient as a reference.

I'll include those references in the documentation, I'm sure it will be
useful to others.
