### ISSUE TITLE
key-binding M->/M-< are not working

### ISSUE THREAD

**Issue by wxie2017** [atlas-engineer/next#572] opened 2020-02-23 08:47 UTC
**Describe the bug**
M->: Jump to bottom of page ==> key-binding is not working, page is not moving
M-<: Jump to top of page ==> key-binding is not working, page is not moving

**Precise recipe to reproduce the issue**
action: hold Alt-key and Shift-key and ,-key or .key after loading a page in NEXT
result: page is not moving

**Information**
- OS name+version: Linux kali 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux
- Kernel name+version: 5.4.0-kali3-amd64
- Graphics card and driver: 00:02.0 VGA compatible controller [0300]: Intel Corporation 3rd Gen Core processor Graphics Controller [8086:0166] (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Lenovo 3rd Gen Core processor Graphics Controller [17aa:3800]
	Flags: bus master, fast devsel, latency 0, IRQ 29
	Memory at d8000000 (64-bit, non-prefetchable) [size=4M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 4000 [size=64]
	Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915
- Desktop environment / Window manager name+version: gdm3, GDM 3.34.1
- Next version (from =M-x next-version= or =next --version=):  "Version 1.5.0-64fa5fd"
- How you installed Next (Guix pack, package manager, build from source): run from source
- SBCL version (if built from source): SBCL 2.0.1.debian
- WebKitGTK+ / PyQt-Webengine version: libwebkit2-sharp-4.0-cil-dev/kali-rolling 2.10.9+git20160917-1.1 amd64
  CLI bindings for WebKitGTK+ 4.0 using GObject Introspection - development

**Comment by Ambrevar** [comment] 2020-02-23 11:40
I can reproduce.
Master has many issue with keys due to the current architecture.
We are fixing this on the `ffi` branch which should be merged very
soon, stay tuned!

**Comment by Ambrevar** [comment] 2020-03-28 13:55
This should now be fixed on master.

**Closed by Ambrevar** 2020-03-28 13:55 UTC
Labels: 2.0

**Comment by jmercouris** [comment] 2020-03-28 16:35
Confirmed fixed on master
