### ISSUE TITLE
Browser needs extreme amounts of RAM

### ISSUE THREAD

**Issue by emwal** [atlas-engineer/next#347] opened 2019-08-30 14:04 UTC
Hi!

When using this (amazing) browser, it needs unusual amounts of RAM (even chrome isn't on this level!). A single tab/buffer needs about 3 to 4 GB and if the tab is killed, the amount of used RAM doesn't decrease, therefore browsing is almost impossible, because it slows the computer to death.

I am on Manjaro Linux, using the quite new AUR-Version
https://aur.archlinux.org/packages/next-browser
since
https://aur.archlinux.org/packages/next-browser-git/
is not updated yet. 

Edit:  Git-Version is up to date, but it isn't shown in the name of the package on the aur website.

**Comment by Ambrevar** [comment] 2019-08-30 14:19
Happy you like it! :)

I haven't experienced this so far, so I'd need more info.  Can you give
a precise recipe:

- The Next version (the commit in particular)
- Which URL you've tried.
- Do you have a ~/.config/next/init.lisp
- The version of WebKitGTK on your system.

> I am on Manjaro Linux, using the quite new AUR-Version
> https://aur.archlinux.org/packages/next-browser
> since
> https://aur.archlinux.org/packages/next-browser-git/
> is not updated yet.

Why would next-browser-git be outdated?  It's supposed to track master.
Doesn't it work for you?

**Comment by emwal** [comment] 2019-08-30 15:28
-` pacman -Q next-browser` returns `next-browser 1.3.0-1`
The AUR-Page points in the "sources"-section to the release https://github.com/atlas-engineer/next/archive/1.3.0.tar.gz 
If you can tell me, where I can find the commit number (probably in the cloned git repo via git status, but that was deleted in the installation process)
- I haven't changed the default config / I do not have created one (yet).
- Tried URLs: deepl.com (a translator) and a generic duckduckgo search
- `pacman -Q webkit2gtk` returns `webkit2gtk 2.24.3-1`

Last time I installed it (after the release of 1.3) via the git version, i got v1.1. I tried it again – and it works. 
The issue persists though.
- `next --version` returns `Next 1.3.0-a05c959`

Hope that helps!

**Comment by emwal** [comment] 2019-08-30 15:38
![RAM_next](https://user-images.githubusercontent.com/38177330/64033515-ea473900-cb4c-11e9-8af1-be08207f52b0.png)

**Comment by Ambrevar** [comment] 2019-08-30 15:40
Yes, a05c959 is master, not 1.3.0.  The PKGBUILD should be fixed.

Can you try if you can reproduce with GNOME Web (a.k.a. Epiphany)?

> Last time I installed it (after the release of 1.3) via the git version, i got v1.1. I tried it again – and it works. 
> The issue persists though.

What do you mean?  That the same memory is in 1.1 as well?

**Comment by emwal** [comment] 2019-08-30 15:52
I installed epiphany – tried it with the same URLs, but couldn't reproduce the problem. 

Sorry for being unclear:
In the past I had next-browser-git installed, but didn't get the upgrade to 1.3.  So I uninstalled it. Since I wanted to try the browser again,  I looked it up on the AUR, seeing, that the description wasn't updated, but the non-git version seemed up to date. After your hint I installed Next again – this time next-browser-git which worked this time, installing the up-to-date-version but with the same problem like the non-git release.

**Comment by alexanderbarbosa** [comment] 2019-08-30 18:11
Noticed that too! 1GB per tab!

**Comment by Ambrevar** [comment] 2019-08-30 21:20
What's your OS?

**Comment by Ambrevar** [comment] 2019-09-02 07:42
@vindarel: Can you reproduce?

**Comment by Ambrevar** [comment] 2019-09-02 07:43
@emwal @alexanderbarbosa Can you try installing Next with [Guix](https://guix.gnu.info) and see if you experience the same issue?
You could also compare with a manual build against master see if that makes a difference.

**Comment by mac1202** [comment] 2019-09-07 07:34
Same issue on manjaro, tried master and 1.3.1 give the same result. Just open the browser to the default getting started page and it eat up my 4go ram laptop in less than 30 seconds.

**Comment by Ambrevar** [comment] 2019-09-07 07:46
What's your WebKitGTK version?

**Comment by mac1202** [comment] 2019-09-07 07:49
extra/webkit2gtk 2.24.4-1

**Comment by vindarel** [comment] 2019-09-09 10:25
No, never experienced this (Mint 19, libwebkit2gtk-4.0-37).

**Comment by Ambrevar** [comment] 2019-09-09 10:41
I believe this package version does not reflect the version of WebKitGTK
being used.
Recent versions include 2.22 and 2.24.

**Comment by alexanderbarbosa** [comment] 2019-09-09 10:41
Hi, 

Ive noticed similar RAM usage of op, having only github and cnn webpages open.

Next is using about 1.5GB RAM.



WARNING: 

I wont claim I know how to correctly measure RAM usage, like Firefox Team do. :)
In a Debian SID Server install with no additional software open in background but StumpWM/SBCL...

SPEC:
Debian SID
StumpWM (255MB RAM)
Webkitgtk: libwebkit2gtk-4.0-37

**Comment by Ambrevar** [comment] 2019-09-09 10:51
Just realized I had misread @emwal 's screenshot: The 98G are the VIRT (virtual) memory.  What you should look at here is the RES (resident) memory.  If you disable the threading view in htop and look at the resident memory column, it should display a memory usage of a couple of hundred megabytes.

@alexanderbarbosa: How do you measure memory usage?

Everyone here: did you notice that Next with 1-2 buffers would hog your system when running?

**Comment by Ambrevar** [comment] 2019-09-09 10:56
That said, @emwal screenshot shows that next eats up 10G of resident memory.  Something is wrong.

**Comment by alexanderbarbosa** [comment] 2019-09-09 10:59
@Ambrevar 

First, Ive found what is StumpWM avg/RAM, then I literally login and do those test with only StumpWM and Browsers.

Log out before testing with Firefox and Chromium

`cat /proc/meminfo | grep MemTotal:`

**Comment by Ambrevar** [comment] 2019-09-09 10:59
To compare, on my computer  next eats some 180MiB of resident memory.

Also this memory is the one used by the Lisp core, so it has nothing to do with the WebKitGTK+ processes.

**Comment by Ambrevar** [comment] 2019-09-09 11:01
@alexanderbarbosa: Can you try installing Next with =guix install next= to compare?

**Comment by alexanderbarbosa** [comment] 2019-09-09 11:38
Point take. 

Next Guix added.

**Comment by alexanderbarbosa** [comment] 2019-09-09 11:47
@Ambrevar 

Weird, with I3wm, Next is using about 200MB less compared to StumpWM.

Its only happens with Next, cause Firefox/Chromium results are bout the same with i3wm!

**Comment by Ambrevar** [comment] 2019-09-09 11:59
I'll test with StumpWM.  This could be a SBCL / Next / StumpWM issue.

**Comment by Ambrevar** [comment] 2019-09-09 12:00
@emwal: Do you run StumpWM?

**Comment by Ambrevar** [comment] 2019-09-09 12:05
Can't reproduce with StumpWM.

Are you running them in the same image?
Or you running anything in the REPL?

**Comment by alexanderbarbosa** [comment] 2019-09-09 12:17
Custom build(upstream) of StumpWM, SBCL and Next...

**Comment by Ambrevar** [comment] 2019-09-09 12:37
Could you try combinations of packaged version of StumpWM and Next?

**Comment by alexanderbarbosa** [comment] 2019-09-09 12:41
@Ambrevar 

Debian StumpWM maintainer abandon it a few versions early 18.1(around 2017), too bad!

**Comment by Ambrevar** [comment] 2019-09-09 12:47
You can install it with Guix! :)

**Comment by alexanderbarbosa** [comment] 2019-09-09 12:54
@Ambrevar 

lol, forgot about that:

StumpWM (guix): 350MB
Next (guix): 1.1GB

Far less ram usage. Still, Firefox (560MB), Chromium (721MB)

**Comment by Ambrevar** [comment] 2019-09-09 13:52
Hmm, still not alright.  Could it depend on the kernel?
I didn't quite get how you measured the RAM consumption.  Can you
elaborate?  Maybe a screenshot / copy-paste of the output?

**Comment by alexanderbarbosa** [comment] 2019-09-09 15:53
StumpWM -> StumpWM + Next/Firefox/Chromium

**Comment by Ambrevar** [comment] 2019-09-09 16:10
I don't understand what you mean.  What's the context?

Killing a buffer does not release the memory in the `next` process, but it should release it in the `next-gtk-webkit` process.

**Comment by alexanderbarbosa** [comment] 2019-09-09 19:24
@Ambrevar  

I beg your pardon.

Ive collected mem ram usage first with only stumpwm, then opened one of next, logout/login, same with firefox and chromium.

As for log:

https://i.ibb.co/7JjTGf8/2019-09-09-162421-1366x768-scrot.png

Sorry, lol.

**Comment by Ambrevar** [comment] 2019-09-09 20:21
OK, so the answer to my question was "you've used `free -m`".

Try this instead, it should give you more accurate results:

--8<---------------cut here---------------start------------->8---
> ps -U $USER -o comm,rss= | grep next
next            173436
next-gtk-webkit 62896
--8<---------------cut here---------------end--------------->8---

**Comment by alexanderbarbosa** [comment] 2019-09-09 22:12
Oh, ok:

Next Guix: 
```
next            118836
next-gtk-webkit 62856
```

Next - Custom Build:

```
```

**Comment by Ambrevar** [comment] 2019-09-10 09:41
In both cases, you see that Next eats up very little RAM.
Something else is wrong, but I'm not sure why Next would be responsible for this.  I can't reproduce on my system.

**Comment by Ambrevar** [comment] 2019-09-10 09:41
Maybe the gst* libraries... Or D-Bus?

**Comment by mac1202** [comment] 2019-09-10 10:06
Here mine result with just the getting started page opened.
```
next            3136336
next-gtk-webkit 42124
```

And ram usage still growing but I close next before it slow down my entire pc.
@alexanderbarbosa don't think you have the same issue as op and me.

**Comment by Ambrevar** [comment] 2019-09-10 10:30
Agreed @mac1202.
The problem is with the Lisp core.
Do you use StumpWM?  How did you install Next and SBCL?

**Comment by mac1202** [comment] 2019-09-10 10:34
I use sway as wm. I installed it from aur.

**Comment by alexanderbarbosa** [comment] 2019-09-10 19:13
@mac1202 
Nope, mine was ram usage compared to firefox/chromium, but it still fairly ok usage. I dont browse that much anyway! ;D

**Comment by mustaqimM** [comment] 2019-12-18 10:57
Try getting the usage with [ps_mem](https://github.com/pixelb/ps_mem)
```sh
Private  +   Shared  =  RAM used	Program
17.7 MiB +  29.9 MiB =  47.6 MiB	next-gtk-webkit
30.3 MiB +  55.8 MiB =  86.1 MiB	WebKitNetworkProcess (3)
82.4 MiB + 159.9 MiB = 242.3 MiB	WebKitWebProcess (3)
161.2 MiB + 161.6 MiB = 322.8 MiB	next
```

This is the ram usage of the PIDs related to next open on the next Documentation page.

**Comment by Ambrevar** [comment] 2020-03-30 08:35
Can anyone reproduce this on master?
Now that we use FFI this issue might be gone.

**Comment by mac1202** [comment] 2020-03-31 10:54
Just tested master issue fixed for me.

**Comment by Ambrevar** [comment] 2020-03-31 12:03
That's great, thanks for testing!

**Comment by lxbarbosa** [comment] 2020-03-31 14:43
here it goes (cnn twitter): 

`next            299008`

**Comment by Ambrevar** [comment] 2020-03-31 14:55
What is this number?  Memory usage?  Which unit?

**Comment by lxbarbosa** [comment] 2020-03-31 16:12
@Ambrevar 
Yep.
` ps -U $USER -o comm,rss= | grep next`

**Comment by Ambrevar** [comment] 2020-03-31 16:16
I guess it's good then!

**Closed** 2020-04-17 14:51 UTC
Labels: bug
