### ISSUE TITLE
Mouse wheel only scrolls downwards

### ISSUE THREAD

**Issue by cbbrowne** [atlas-engineer/next#455] opened 2019-10-07 16:35 UTC
**Describe the bug**

My mouse has a wheel; when I rotate it, the Next buffer scrolls upwards regardless of the direction of rotation of the wheel.

**Precise recipe to reproduce the issue**

Browse a web page containing more material than fits in one screen so that it has a scroll bar.

Rotate mouse wheel in either direction; watch it scroll upwards in either case.

**Information**
- OS name+version: Debian bullseye/sid
- Kernel name+version: Linux 4.19.0-5
- Graphics card and driver: Intel i965, fbdev, vesa
- Desktop environment / Window manager name+version: stumpwm 0.9.9-716
- Next version (from =M-x next-version= or =next --version=): 1.3.4-33cfe86
- How you installed Next (Guix pack, package manager, build from source): build from source
- SBCL version (if built from source): 1.5.6.debian
- WebKitGTK+ / PyQt-Webengine version: 2.24-4-1

**Comment by Ambrevar** [comment] 2019-10-07 18:07
This is an issue with StumpWM.

A workaround is to export this before running Next:

--8<---------------cut here---------------start------------->8---
export GDK_CORE_DEVICE_EVENTS=1
--8<---------------cut here---------------end--------------->8---

I'm not sure why that is and I'm not sure how to fix it properly from
Next only.

@noogie?

**Comment by RoGryza** [comment] 2019-10-09 12:13
I have a similar problem (also using StumpWM), I can't scroll with the mouse wheel at all. Setting `GDK_CORE_DEVICE_EVENTS=1` causes the scroll wheel to select text wheen rotated

**Comment by Ambrevar** [comment] 2019-10-09 12:23
We should ask the StumpWM people, they might know more about this.

**Comment by Ambrevar** [comment] 2019-10-09 12:25
Actually, maybe not.
See this: https://github.com/stumpwm/stumpwm/issues/372

I'll add it to the readme.

**Comment by RoGryza** [comment] 2019-10-09 15:08
I've added `export GDK_CORE_DEVICE_EVENTS=1` to my xinitrc, I can scroll down now but not up. Any hints on how to check if this is caused by StumpWM or next?

**Comment by Ambrevar** [comment] 2019-10-09 15:42
Sorry, no idea :(

**Comment by jmercouris** [comment] 2019-10-09 18:27
Just to clarify, regardless of the direction you spin your mousewheel it scrolls down?

**Comment by cbbrowne** [comment] 2019-10-09 19:49
> Just to clarify, regardless of the direction you spin your mousewheel it scrolls down?

That's right.  WIth GDK_CORE_DEVICE_EVENTS=1, it behaves a bit differently now; a line or so of text gets selected/highlighted; it still doesn't scroll upwards.  So this isn't quite a fix :-(  Spinning "down" has (seemingly) always worked per expectations, but spinning "up," not so much.

I'm using stumpwm, so it's conceivable that that affects the behaviour.  However, I have a Firefox instance running in the same session, and the mousewheel behaves as expected, where spinning in each direction scrolls the window in each direction.  So it sure wasn't intuitive to blame stumpwm for this.

**Comment by Ambrevar** [comment] 2019-10-10 08:16
This may have to do with the way we generate input events on the
platform port.

Will work on it.

**Comment by Ambrevar** [comment] 2020-03-05 15:25
This might be fixed on master.
Beware that master is quite experimental at this point, so expect some rough edges.
2.0 coming soon!

**Comment by jmercouris** [comment] 2020-03-05 17:25
This *is* fixed on master. We don't take over mouse scroll anymore.

**Closed** 2020-03-28 14:05 UTC
Labels: 2.0
