### ISSUE TITLE
Emacs keybindings for input/text forms

### ISSUE THREAD

**Issue by smabie** [atlas-engineer/next#732] opened 2020-05-14 08:41 UTC
Hi, I was wondering if there are any plans on supporting the standard emacs editing keybindings for text form?  If not, I could be interested in doing it myself, provided someone point me in the right direction.

**Comment by Ambrevar** [comment] 2020-05-14 09:27
There definitely is!

An easy workaround that many other browsers use (e.g. Qutebrowser) is to
add a command to edit the text form in an external browser.

(Note that if you use EXWM, it's already possible to do this with https://github.com/agzam/exwm-edit/.)

Ideally, clicking on input text tags could enable the text-editor-mode
with special bindings.  To work properly, we need text editing functions
such as "forward-word" or "beginning-of-line".

1. We could leverage the code that https://github.com/cxxxr/lem wrote.

2. Then we turn it into a text-editor library.

3. Finally we implement text-editor-mode which binds commands to the
   editing function from the library.

Let me know if you need more clarifications about the different points.

**Comment by Ambrevar** [comment] 2020-05-31 08:41
Closing since this is a duplicate of #557.

**Closed by Ambrevar** 2020-05-31 08:41 UTC
