### ISSUE TITLE
Decode percent encoded characters in URIs

### ISSUE THREAD

**Issue by arunisaac** [atlas-engineer/next#695] opened 2020-04-24 16:18 UTC
URIs with percent encoded Unicode characters should be decoded before being displayed to the user on the mode line, history, etc. Percent encoded characters are not human readable and this makes reading URIs in non-English languages painful.

Thank you!

**Comment by Ambrevar** [comment] 2020-04-24 17:07
Will do!

Can you give me a URL to test with?

**Comment by Ambrevar** [comment] 2020-04-24 17:21
When pressing C-w in the minibuffer (copy-url), should we copy the
decoded URL or the raw URL?

At the moment we use the OBJECT-STRING method both to tab-complete and
copy.

For URLs, tab-completion must insert the decoded URLs otherwise it would
not match the candidates which should also be decoded.

**Comment by arunisaac** [comment] 2020-04-24 20:10
Here are a couple of examples, one Tamil and the other French.

https://ta.wikipedia.org/wiki/%E0%AE%B5%E0%AE%BF%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AE%BF%E0%AE%AA%E0%AF%8D%E0%AE%AA%E0%AF%80%E0%AE%9F%E0%AE%BF%E0%AE%AF%E0%AE%BE

https://fr.wikipedia.org/wiki/Wikip%C3%A9dia

> When pressing C-w in the minibuffer (copy-url), should we copy the
> decoded URL or the raw URL?

I think copy-url should copy the raw URL (the one with the percent
encoded characters). That way, the copied URL will still be valid when
pasted into other programs. This is also what Firefox does. I just
checked.

**Comment by Ambrevar** [comment] 2020-04-25 07:47
Thanks!

Does this mean we need 3 string representation methods?

- object-display to display the candidates,
- object-string for tab completion,
- object-copy for copy?

Or can we be smarter?

Maybe tab-completion could insert object-display until the first space?
I'll try that.

**Comment by Ambrevar** [comment] 2020-04-25 09:01
Fixed in 8f394a5e7655b9d85823e96101627b13b2dfb7a2.

> Maybe tab-completion could insert object-display until the first space?
> I'll try that.

This does not work because the URL is not always on first position
(e.g. switch-buffer).  Instead I decided to insert the object-string and
if it is a URL then we decode it.

**Comment by Ambrevar** [comment] 2020-04-25 09:02
Feel free to reopen if you can spot URLs that should be decoded.

**Closed by Ambrevar** 2020-04-25 09:02 UTC

**Comment by arunisaac** [comment] 2020-04-25 12:20
Thanks, works nicely! :-)

> Feel free to reopen if you can spot URLs that should be decoded.

Sure!

**Comment by arunisaac** [comment] 2020-06-17 13:33
I think there has been a regression. When I try to follow a link on a page, in the list of URLs offered for completion, the URLs are not decoded. For example, try on this page: https://ta.wiktionary.org/wiki/%E0%AE%89%E0%AE%B3%E0%AF%81%E0%AE%A8%E0%AF%8D%E0%AE%A4%E0%AF%81

**Comment by Ambrevar** [comment] 2020-06-17 17:31
I don't think this is a regression, I think this was simply forgotten! :p 
Should be fixed in cb4977bf79fcd0b359b4faf0994a7653a6af3853.

**Comment by arunisaac** [comment] 2020-06-18 13:53
Ok, thanks for the fix!

But, I am unable to test this immediately since the guix build using
`guix build -f build-scripts/guix.scm` fails. It seems to be because
cluffer was not found. Perhaps cluffer is a new dependency that needs to
be packaged and added to nyxt's package definition?

**Comment by Ambrevar** [comment] 2020-06-18 14:04
Yes, this is due to the merge of yesterday.
I'm hard at work on updating the Guix dependeencies, stay tuned!

**Comment by jmercouris** [comment] 2020-06-18 14:16
You can blame me for that :-O

**Comment by Ambrevar** [comment] 2020-06-18 16:17
Should be fixed with 15a85ea0d8096e332dc83e1c9c1342153d93d8dc!
Guix pull, git pull nyxt, and try again :)

**Comment by arunisaac** [comment] 2020-06-18 22:52
Nyxt builds fine now and the fix works. Thanks, I appreciate your hard
work! :-)
