### ISSUE TITLE
How does the Next deal with the videos and audio HTML5?

### ISSUE THREAD

**Issue by noloop** [atlas-engineer/next#191] opened 2019-02-16 20:40 UTC
I'm looking for the project, it attracted me a lot, in time I'm looking for a simple and customizable browser. So I downloaded the Next, I liked it a lot, but he did not open the videos, I get the message:

"Your browser does not currently recognize any of the video formats available."

I do not know if something is wrong here or the Next can not see videos. I wonder if the Next supports videos and audios? And if Next do not support, what could be done to change that, what are the limitations.

**Comment by jmercouris** [comment] 2019-02-17 00:21
hi @noloop thank you for your interest in the project! Did you make sure that you have all of the dependencies for Linux installed? Did you install from source? There are options dependencies for video codecs. A little more information about your set-up could help us debug this issue! thank you :)

**Comment by noloop** [comment] 2019-02-17 00:28
I'm on Void Linux, I downloaded this link:

https://next.atlas.engineer/static/release/next-linux-gtk-webkit.tar.lz

So it is possible that some codecs are missing, which ones should I have? or is it already included in the unzipped "gnu" directory?

**Comment by Ambrevar** [comment] 2019-02-17 11:02
This is a known issue with Guix and its `gst-*` packages.  I'll get down to fix it as soon as possible.
In the mean time @noloop you can compile Next following the instructions in the [developer's README](https://github.com/atlas-engineer/next/tree/master/documents).

A Void Linux package would also be neat :D

**Comment by Ambrevar** [comment] 2019-05-08 18:12
This should be fixed in Next 1.2.1. Feel free to re-open if you still experience the issue.

**Closed by Ambrevar** 2019-05-08 18:12 UTC

**Comment by nolanwrightdev** [comment] 2019-07-30 22:59
Just installed this browser via AUR. Getting that same error message: "Your browser does not currently recognize any of the video formats available." What dependencies might I might be missing? I have webkit2gtk installed already.

**Comment by alexanderbarbosa** [comment] 2019-07-30 23:14
@nolanwrightdev  

AUR should install all dependencies, I dont think its the issue!

**Comment by nolanwrightdev** [comment] 2019-07-31 00:13
Hm well idk then. I installed the browser via `yay -S next-browser-git`. Let me know if you want any details about my system.

**Comment by Ambrevar** [comment] 2019-07-31 07:05
The dependencies to display HTML5 content are optional.  From the
PKGBUILD:

```
gst-plugins-bad (gst-plugins-bad-git) (optional) – for HTML5 audio/video
gst-plugins-base (gst-plugins-base-git) (optional) – for HTML5 audio/video
gst-plugins-good (gst-plugins-good-git) (optional) – for HTML5 audio/video
gst-plugins-ugly (gst-plugins-ugly-git) (optional) – for HTML5 audio/video
gstreamer (gstreamer-git) (optional) – for HTML5 audio/video
```

Install the above and you should be good to go!

**Comment by nolanwrightdev** [comment] 2019-07-31 10:00
That did indeed solve the issue. Thanks, @Ambrevar.

**Comment by noloop** [comment] 2019-11-05 15:22
[next-gtk-webkit.log](https://github.com/atlas-engineer/next/files/3809943/next-gtk-webkit.log)
> The dependencies to display HTML5 content are optional. From the PKGBUILD: ``` gst-plugins-bad (gst-plugins-bad-git) (optional) – for HTML5 audio/video gst-plugins-base (gst-plugins-base-git) (optional) – for HTML5 audio/video gst-plugins-good (gst-plugins-good-git) (optional) – for HTML5 audio/video gst-plugins-ugly (gst-plugins-ugly-git) (optional) – for HTML5 audio/video gstreamer (gstreamer-git) (optional) – for HTML5 audio/video ``` Install the above and you should be good to go!

I did download the version 1.3.4 and I installed all packages and still can't see videos.

**Comment by Ambrevar** [comment] 2019-11-05 16:22
Maybe delete ~/.cache/gstreamer-1.0 and try again.
Can you see videos with Epiphany?

**Comment by noloop** [comment] 2019-11-05 17:31
> Maybe delete ~/.cache/gstreamer-1.0 and try again. Can you see videos with Epiphany?

I did this, and it still doesn't work. In Epiphany I can watch videos.

**Comment by noloop** [comment] 2019-11-05 17:50
I try compile of the next source and i get:


```
unhandled condition in --disable-debugger mode, quitting

Compilation failed.
Make sure the 'xclip' binary and the 'sqlite' and 'libfixposix' development files are available on your system.
make: *** [Makefile:36: next] Error 1
```
I have all dependencies installed.

**Comment by Ambrevar** [comment] 2019-11-05 18:41
What do you mean, either?  The Void Linux package does not work?

Can you share the error output you get when compiling?

**Comment by noloop** [comment] 2019-11-05 18:47
> What do you mean, either? The Void Linux package does not work? Can you share the error output you get when compiling?

It works, but I only discovered it after trying to compile, I searched before and don't find, but someone built the package. But now that I've tried to compile I would like to be able to do so.

**Comment by Ambrevar** [comment] 2019-11-05 19:14
From the error output, you need to install openssl.
If I recall correctly, Void Linux might have an openssl-dev which you'll
need for the .so symlinks.

**Comment by noloop** [comment] 2019-11-05 20:23
> From the error output, you need to install openssl. If I recall correctly, Void Linux might have an openssl-dev which you'll need for the .so symlinks.

I installed and I try again:

```lisp
;;;...
Switching to the BALLAND2006 optimizer
WARNING: redefining CL-ANNOT.STD:EXPORT* in DEFMACRO
WARNING: redefining CL-ANNOT.CLASS:EXPORT-ACCESSORS in DEFMACRO
[undoing binding stack and other enclosing state... done]
[performing final GC... done]
[defragmenting immobile space... (fin,inst,fdefn,code,sym)=3690+2150+35968+32954+28238... done]
[saving current Lisp image into /home/noloop/common-lisp/next/next:
writing 0 bytes from the read-only space at 0x50000000
compressed 0 bytes into 8 at level -1
writing 1264 bytes from the static space at 0x50100000
compressed 32768 bytes into 439 at level -1
writing 74481664 bytes from the dynamic space at 0x1000000000
compressed 74481664 bytes into 14663448 at level -1
writing 2985984 bytes from the immobile space at 0x50300000
compressed 3014656 bytes into 790250 at level -1
writing 22913024 bytes from the immobile space at 0x52100000
compressed 22937600 bytes into 6935654 at level -1
done]
make -C ports/gtk-webkit || (printf "\n%s\n%s\n" "Compilation failed." "Make sure 'webkitgtk >=2.22' development files are available on your system." && exit 1)
make[1]: Entering directory '/home/noloop/common-lisp/next/ports/gtk-webkit'
cc `pkg-config --cflags webkit2gtk-4.0`   -c -o next-gtk-webkit.o next-gtk-webkit.c
/bin/sh: 1: pkg-config: not found
next-gtk-webkit.c:6:10: fatal error: gtk/gtk.h: No such file or directory
    6 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[1]: *** [<builtin>: next-gtk-webkit.o] Error 1
make[1]: Leaving directory '/home/noloop/common-lisp/next/ports/gtk-webkit'

Compilation failed.
Make sure 'webkitgtk >=2.22' development files are available on your system.
make: *** [Makefile:69: gtk-webkit] Error 1
```

**Comment by noloop** [comment] 2019-11-05 23:01
I cleaned up everything I could and tried again, and now it compiles, so I change my file "~/.config/next/init.lisp". And I tried to run next, and I get the same as I'm getting when running next void-linux package:

```
Next version 1.3.4-d3ece6a
Loading configuration from #P"/home/noloop/.config/next/init.lisp"...
 <INFO> [16:53:56] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: "NIL">)
Unhandled SIMPLE-ERROR in thread #<SB-THREAD:THREAD "Anonymous thread" RUNNING
                                    {1005BFAF03}>:
  No server addresses left to try to open.

Backtrace for: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005BFAF03}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<SIMPLE-ERROR "No server addresses left to try to open." {1005E00A83}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK *INVOKE-DEBUGGER-HOOK* #<SIMPLE-ERROR "No server addresses left to try to open." {1005E00A83}>)
2: (INVOKE-DEBUGGER #<SIMPLE-ERROR "No server addresses left to try to open." {1005E00A83}>)
3: (ERROR "No server addresses left to try to open.")
4: ((LAMBDA NIL :IN DBUS/PROTOCOLS:OPEN-CONNECTION))
5: (DBUS/CONVENIENCE::CALL-WITH-OPEN-BUS #<CLOSURE (LAMBDA (NEXT::BUS) :IN INITIALIZE-INSTANCE) {1005DF7D1B}> #<event base, 0 FDs monitored, using: #<epoll(4) multiplexer> {1005DF6353}> (#<DBUS/TRANSPORT-UNIX:UNIX-SERVER-ADDRESS {1005DF7BD3}>))
6: ((LAMBDA NIL :IN INITIALIZE-INSTANCE))
7: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
8: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
9: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
10: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
11: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
12: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {7F6270CC6D7B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005BFAF03}>> NIL T NIL)
13: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "Anonymous thread" RUNNING {1005BFAF03}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {1005BFAEAB}> NIL)
14: ("foreign function: call_into_lisp")
15: ("foreign function: new_thread_trampoline")

unhandled condition in --disable-debugger mode, quitting
```

**Comment by Ambrevar** [comment] 2019-11-06 08:33
You need dbus.  In particular, dbus-broker is not supported.

**Comment by noloop** [comment] 2019-11-06 10:33
> You need dbus. In particular, dbus-broker is not supported.

I have installed:

```
[*] dbus-1.12.16_1                                     Message bus system
[*] dbus-devel-1.12.16_1                               Message bus system - developmen...
[*] dbus-glib-0.110_1                                  GLib bindings for D-Bus
[*] dbus-glib-devel-0.110_1                            GLib bindings for D-Bus - devel...
[*] dbus-libs-1.12.16_1                                Message bus system - shared lib...
[*] dbus-x11-1.12.16_1                                 Message bus system - X11 support
```

**Comment by Ambrevar** [comment] 2019-11-06 11:19
What's your window manager / desktop environment?

Can you start next with the following?

   export $(dbus-launch) ; next

**Comment by noloop** [comment] 2019-11-06 12:03
> export $(dbus-launch) ; next

This doesn't work.

I use https://github.com/baskerville/bspwm

**Comment by Ambrevar** [comment] 2019-11-06 12:10
Are you using systemd?

Can you report the output of

  ps -U $USER | grep dbus

**Comment by noloop** [comment] 2019-11-06 12:26
> export $(dbus-launch) ; next

Sorry, I was wrong, yes it worked by exporting `$(dbus-launch)`. But it was so slow that it crashed everything.

but already checked, it's my memory that is over, but there is still something that happens. When I close next and open again, I get:

```
Next version 1.3.4
Loading configuration from #P"/home/noloop/.config/next/init.lisp"...
 <INFO> [06:18:03] next remote.lisp (initialize-instance :after remote-interface) -
  D-Bus addresses: (#<Unix socket address: @"/tmp/dbus-Z6H3lsHHny">)
 <INFO> [06:18:03] next remote.lisp (initialize-instance :after remote-interface) -
  Bus connection name: :1.626
 <INFO> [06:18:03] next port.lisp (run-program port) -
  Current directory: /home/noloop/common-lisp/next-1.3.4/
 <INFO> [06:18:03] next port.lisp (run-program port) -
  Platform port path: /home/noloop/common-lisp/next-1.3.4/ports/gtk-webkit/next-gtk-webkit
 <INFO> [06:18:03] next port.lisp (run-program port) -
  Platform port arguments: NIL
 <INFO> [06:18:03] next port.lisp (run-program port) -
  Platform port log file: /home/noloop/.local/share/next/next-gtk-webkit.log
<ERROR> [06:18:04] next base.lisp (start fun2) -
  Could not connect to platform port: /home/noloop/common-lisp/next-1.3.4/ports/gtk-webkit/next-gtk-webkit
Make sure the platform port executable is either in the
PATH or set in you ~/.config/next/init.lisp, for instance:

     (setf +platform-port-command+
         "~/common-lisp/next/ports/gtk-webkit/next-gtk-webkit")
```

and I have to start over, sometimes this is repeated for more than once.

> Are you using systemd?

Void-linux uses runit, not systemd.

**Comment by Ambrevar** [comment] 2019-11-06 14:32
If Next crashes, it is possible that a hung process is left running in
the background.  Make sure to kill `next` and `next-gtk-webkit` before
trying again.

**Comment by noloop** [comment] 2019-11-06 14:34
> If Next crashes, it is possible that a hung process is left running in the background. Make sure to kill `next` and `next-gtk-webkit` before trying again.

but `C-x C-c` should not do that?

**Comment by Ambrevar** [comment] 2019-11-06 14:58
Maybe a misunderstanding:

- C-x C-c should quit Next.

- In all cases, C-x C-c or not, if Next crashes the processes might not
  get cleaned up properly.  Just make sure no Next process is running
  before starting it again.

**Comment by noloop** [comment] 2019-11-06 15:28
> crashes

But this occurs even when it does not crashes.

**Comment by Ambrevar** [comment] 2019-11-06 16:09
What occurs?  It seems that you have different issues.  Can you
list all the different cases?

**Comment by noloop** [comment] 2019-11-06 16:14
> What occurs? It seems that you have different issues. Can you list all the different cases?

No, we have all solved so far, now there is only one, that when I open Next and then close it, the next time I open it I have to try more than once to get it open.

**Comment by Ambrevar** [comment] 2019-11-06 16:22
So can you check the background processes after you've quit Next?  Any "next" something running?

**Comment by noloop** [comment] 2019-11-06 18:16
> So can you check the background processes after you've quit Next? Any "next" something running?

During next execution:

![before-quit-next](https://user-images.githubusercontent.com/25625276/68325163-a53d0700-00a7-11ea-910b-d91c1969320a.png)

after `C-x C-c`:

![after-quit-next](https://user-images.githubusercontent.com/25625276/68325201-b4bc5000-00a7-11ea-8874-67b8b19f3511.png)

Perhaps is the `WebKitNetworkPr` or `at-spi-bus-laun` that doesn't should be here. But the Next should not that kill the `WebKitNetworkPr`?

**Comment by noloop** [comment] 2019-11-06 22:26
I restarted my system and run only the Next. 

Here, all way until crashes the Next. When I watch a video the Next crashes with or whitout free memory.

[next.log](https://github.com/atlas-engineer/next/files/3816997/next.log)

**Comment by noloop** [comment] 2019-11-07 00:08
I downloaded the "next-pyqt-webengine" and I can watch video whitout crashes the Next. But when I try write here by example, It doesn't work the Capslook and also doesn't work the space.

**Comment by Ambrevar** [comment] 2019-11-07 12:25
Indeed, it seems that Next is not closing properly on your system.
What if you kill the window instead of pressing `C-x C-c`?

- WebKitGTK tends to crash a lot when watching videos.  This is not directly a Next issue, although we could probably do better.
- PyQt is experimental, it still has some issues.

**Comment by noloop** [comment] 2019-11-07 12:37
I think the problem is that `WebKitGTK` always crashes and Next can't close properly, because with` PyQt` with `C-x C-c` it seems to kill correctly every time I try.

This is bad because the two available backends do not work.

**Comment by Ambrevar** [comment] 2019-11-07 12:50
You seem to be the first one reporting this issue.  There could be an
issue with the WebKitGTK package on Void Linux.

Maybe ask the Void Linux packagers?
Could you try another distribution?

Else you can build it using Guix:

  guix build -f build-scripts/guix.scm

**Comment by noloop** [comment] 2019-11-07 12:57
How the problem is the webkit package if `Epiphany` works well with it without crashing?

**Comment by Ambrevar** [comment] 2019-11-07 15:04
I'm just guessing here.  I can't reproduce your issue, so it's not easy
to investigate on my side :)

Some distributions maybe ship different version of WebKitGTK.  Which
version do you use to link against Next?
Which one is used by Epiphany (if different)?

**Comment by noloop** [comment] 2019-11-07 16:00
I understand, this doesn't is a block for me not use the Next, but l would like to find the problem. My version webkit2gtk that is used by Next and Epiphany:

```
webkit2gtk-2.26.0_1
webkit2gtk-devel-2.26.0_1

```
This is:

`/usr/lib/libwebkit2gtk-4.0.so.37.39.1`
