### ISSUE TITLE
Arch: whenever minibuffer is used, next freezes

### ISSUE THREAD

**Issue by Dav1d23** [atlas-engineer/next#182] opened 2018-12-25 17:38 UTC
I've built next from sources (commit: 7a62fa280e6ac7a5b51f7b3b1d00cfea9df1f608) and I'm able to start it up.
But I have several freezes, and there is a systematic one whenever I open the minibuffer (M-x) and scroll down using the arrows. Next freezes and there is no way to get it back.

Is there a way to have debug informations, in order to give you more details?

**Comment by Ambrevar** [comment] 2018-12-25 18:44
I can reproduce after a lot of up/down keypresses (20-30).
How long does it take for you?

I believe this issue is due to the major cause of instability in Next: it might be something with having 2 webkit views in the same window.

@jmercouris: Can you reproduce?  You might have to press up/down a lot.  If not, then it's  WebKitGTK+-specific.

**Comment by Ambrevar** [comment] 2018-12-25 18:45
I can reproduce on `C-l`, so this must be a global issue.

**Comment by jmercouris** [comment] 2018-12-25 18:58
I cannot reproduce, I can even spam C-g with no problem.

**Comment by Ambrevar** [comment] 2018-12-26 11:32
I found a way to reproduce (assuming it's the same issue): keep
pressing "C-g", Next should hang immediately.

@jmercouris: does it work for you?

@Dav1d23: can you reproduce?

**Comment by jmercouris** [comment] 2018-12-26 12:38
@Ambrevar that's what I meant when I said I can spam "C-g" without it hanging. I can continuously press it. I suspect, that probably what the issue is in WebKitGTK it doesn't like if there is more than one javascript request evaluating from the Lisp Core at once.

**Comment by Dav1d23** [comment] 2018-12-27 11:04
The best way to reproduce it right now is:
* C-l www.google.com
* M-x
* PageUp PageDown PageUp PageDown PageUp PageDown PageUp PageDown
* press delete to clean the minibuffer

BTW, I tried again and just C-g a couple of time (fast) on the next quickstart page did the job.

**Comment by Dav1d23** [comment] 2018-12-28 09:44
Here are some logs

`** Message: 10:43:17.883: XML-RPC message: PUSH-KEY-EVENT (keycode, keyval, modifiers, window id) = (42, 'g', ['C'], '0')
** Message: 10:43:17.888: XML-RPC message: CONSUME-KEY-SEQUENCE, window id 0
** Message: 10:43:17.894: Method name: window.active
** Message: 10:43:17.894: Method parameter(s): 0
** Message: 10:43:17.897: Method name: window.set.minibuffer.height
** Message: 10:43:17.897: Method parameter(s): window id 0, minibuffer height 0
** Message: 10:43:17.897: Window 0 resizes its minibuffer to 0
** Message: 10:43:17.897: Method result(s): minibuffer preferred height 0
** Message: 10:43:17.929: Method name: window.active
** Message: 10:43:17.929: Method parameter(s): 0
** Message: 10:43:17.932: Method name: minibuffer.evaluate.javascript
** Message: 10:43:17.932: Method parameter(s): window id 0
** Message: 10:43:17.932: Method result(s): callback id 2
** Message: 10:43:17.938: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 2)
** Message: 10:43:17.939: Method name: window.active
** Message: 10:43:17.939: Method parameter(s): 0
** Message: 10:43:17.941: Method name: buffer.evaluate.javascript
** Message: 10:43:17.941: Method parameter(s): buffer id 0
** Message: 10:43:17.941: Method result(s): callback id 4
** Message: 10:43:17.944: Method name: window.active
** Message: 10:43:17.944: Method parameter(s): 0
** Message: 10:43:17.945: Method name: buffer.evaluate.javascript
** Message: 10:43:17.945: Method parameter(s): buffer id 0
** Message: 10:43:17.945: Method result(s): callback id 5
** Message: 10:43:17.949: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 4)
** Message: 10:43:17.949: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 5)
** Message: 10:43:17.956: Method name: window.active
** Message: 10:43:17.956: Method parameter(s): 0
** Message: 10:43:17.957: Method name: window.active
** Message: 10:43:17.957: Method parameter(s): 0
** Message: 10:43:17.958: Method name: minibuffer.evaluate.javascript
** Message: 10:43:17.958: Method parameter(s): window id 0
** Message: 10:43:17.958: Method result(s): callback id 3
** Message: 10:43:17.958: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 3)
** Message: 10:43:17.959: Method name: window.active
** Message: 10:43:17.959: Method parameter(s): 0
** Message: 10:43:17.960: Method name: minibuffer.evaluate.javascript
** Message: 10:43:17.960: Method parameter(s): window id 0
** Message: 10:43:17.960: Method result(s): callback id 4
** Message: 10:43:17.960: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 4)
** Message: 10:43:17.960: Method name: window.active
** Message: 10:43:17.960: Method parameter(s): 0
** Message: 10:43:17.961: Method name: minibuffer.evaluate.javascript
** Message: 10:43:17.961: Method parameter(s): window id 0
** Message: 10:43:17.961: Method result(s): callback id 5
** Message: 10:43:17.962: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 5)
** Message: 10:43:17.962: Method name: window.active
** Message: 10:43:17.962: Method parameter(s): 0
** Message: 10:43:17.963: Method name: window.set.minibuffer.height
** Message: 10:43:17.963: Method parameter(s): window id 0, minibuffer height 200
** Message: 10:43:17.963: Window 0 resizes its minibuffer to 200
** Message: 10:43:17.963: Method result(s): minibuffer preferred height 200
** Message: 10:43:17.969: Method name: window.active
** Message: 10:43:17.969: Method parameter(s): 0
** Message: 10:43:17.971: Method name: window.active
** Message: 10:43:17.971: Method parameter(s): 0
** Message: 10:43:17.972: Method name: window.set.title
** Message: 10:43:17.972: Method parameter(s): 0, Next - Next - undefined
** Message: 10:43:17.973: Method name: window.active
** Message: 10:43:17.973: Method parameter(s): 0
** Message: 10:43:17.974: Method name: window.set.title
** Message: 10:43:17.974: Method parameter(s): 0, Next - undefined - https://next.atlas.engineer/quickstart
** Message: 10:43:17.975: Method name: window.active
** Message: 10:43:17.975: Method parameter(s): 0
** Message: 10:43:17.976: Method name: window.active
** Message: 10:43:17.976: Method parameter(s): 0
** Message: 10:43:17.977: Method name: minibuffer.evaluate.javascript
** Message: 10:43:17.977: Method parameter(s): window id 0
** Message: 10:43:17.977: Method result(s): callback id 6
** Message: 10:43:17.978: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 6)
** Message: 10:43:17.978: Method name: window.active
** Message: 10:43:17.978: Method parameter(s): 0
** Message: 10:43:17.979: Method name: minibuffer.evaluate.javascript
** Message: 10:43:17.979: Method parameter(s): window id 0
** Message: 10:43:17.979: Method result(s): callback id 7
** Message: 10:43:17.980: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 7)
** Message: 10:43:17.980: Method name: window.active
** Message: 10:43:17.980: Method parameter(s): 0
** Message: 10:43:17.981: Method name: minibuffer.evaluate.javascript
** Message: 10:43:17.981: Method parameter(s): window id 0
** Message: 10:43:17.981: Method result(s): callback id 8
** Message: 10:43:17.981: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (0, ..., 8)
** Message: 10:43:17.982: Method name: window.active
** Message: 10:43:17.982: Method parameter(s): 0
** Message: 10:43:17.983: Method name: window.set.minibuffer.height
** Message: 10:43:17.983: Method parameter(s): window id 0, minibuffer height 200
** Message: 10:43:17.983: Window 0 resizes its minibuffer to 200
** Message: 10:43:17.983: Method result(s): minibuffer preferred height 200
** Message: 10:43:17.984: Method name: window.active
** Message: 10:43:17.984: Method parameter(s): 0
** Message: 10:43:17.985: Method name: window.active
** Message: 10:43:17.985: Method parameter(s): 0
** Message: 10:43:17.986: Method name: window.set.title
** Message: 10:43:17.986: Method parameter(s): 0, Next - <ul></ul> - undefined
** Message: 10:43:19.508: XML-RPC message: PUSH-KEY-EVENT (keycode, keyval, modifiers, window id) = (42, 'g', ['C'], '0')
** Message: 10:43:19.512: XML-RPC message: CONSUME-KEY-SEQUENCE, window id 0
** Message: 10:43:19.518: Method name: window.active
** Message: 10:43:19.518: Method parameter(s): 0
** Message: 10:43:19.521: Method name: buffer.make
** Message: 10:43:19.521: Method parameter(s): /home/david.petroni/.local/share/next/cookies.txt
** Message: 10:43:19.522: Method result(s): buffer id 1
** Message: 10:43:19.525: Method name: window.set.active.buffer
** Message: 10:43:19.526: Method parameter(s): window id 0, buffer id 1
** Message: 10:43:19.526: Window 0 switches from buffer 0 to 1
** Message: 10:43:21.499: XML-RPC message: PUSH-KEY-EVENT (keycode, keyval, modifiers, window id) = (42, 'g', ['C'], '0')

** (next-gtk-webkit:16956): WARNING **: 10:43:21.505: Malformed XML-RPC response: The slot NEXT::MODE is unbound in the object #<BUFFER {1005CFE353}>.
** Message: 10:43:22.323: XML-RPC message: PUSH-KEY-EVENT (keycode, keyval, modifiers, window id) = (42, 'g', ['C'], '0')

** (next-gtk-webkit:16956): WARNING **: 10:43:22.329: Malformed XML-RPC response: The slot NEXT::MODE is unbound in the object #<BUFFER {1005CFE353}>.
`

I'm just C-g on the fist page, and now it is stuck.

**Comment by jmercouris** [comment] 2018-12-28 23:16
sorry, touchscreen caused me to accidentally close issue

**Comment by FrozenPigs** [comment] 2019-03-24 13:12
This is what I can get by spamming C-g:
```
** Message: 13:07:40.328: Window 1 switches from buffer (null) to 5
** Message: 13:07:40.573: Method name: buffer.evaluate.javascript
** Message: 13:07:40.573: Method parameter(s): buffer id 5
** Message: 13:07:40.574: Method result(s): callback id 1
** Message: 13:07:40.574: XML-RPC message: BUFFER-JAVASCRIPT-CALL-BACK (buffer id, javascript, callback id) = (5, ..., 1)
** Message: 13:07:41.057: XML-RPC message: BUFFER-DID-COMMIT-NAVIGATION ('5', 'https://next.atlas.engineer/quickstart')
** Message: 13:07:51.161: XML-RPC message: PUSH-KEY-EVENT (keycode, keyval, modifiers, window id) = (30, 'g', ['C'], '1')

** (next-gtk-webkit:8268): WARNING **: 13:07:51.162: Malformed XML-RPC response: Failed to parse response XML
** Message: 13:07:51.348: XML-RPC message: PUSH-KEY-EVENT (keycode, keyval, modifiers, window id) = (30, 'g', ['C'], '1')

** (next-gtk-webkit:8268): WARNING **: 13:07:51.349: Malformed XML-RPC response: Failed to parse response XML
** Message: 13:07:51.515: XML-RPC message: PUSH-KEY-EVENT (keycode, keyval, modifiers, window id) = (30, 'g', ['C'], '1')

** (next-gtk-webkit:8268): WARNING **: 13:07:51.516: Malformed XML-RPC response: Failed to parse response XML
** Message: 13:07:51.676: XML-RPC message: PUSH-KEY-EVENT (keycode, keyval, modifiers, window id) = (30, 'g', ['C'], '1')

```

**Comment by jmercouris** [comment] 2019-03-24 15:12
Hi, firstly, thank you for the detailed logs. It seems to me that S-XML-RPC is sending malformed XML-RPC. We'll have to take a look at the raw request to verify this.

What is interesting though is that somehow something happens and then there exists a buffer without a mode? I wonder how that is possible...

**Comment by FrozenPigs** [comment] 2019-03-26 22:38
> What is interesting though is that somehow something happens and then there exists a buffer without a mode? I wonder how that is possible...
On that point I am using exwm so could be related to #184 in some way.

**Comment by Ambrevar** [comment] 2019-03-27 17:29
I've tried using Next without EXWM (with StumpWM), and I can reproduce the hangs / crashes.  I don't think that EXWM has anything to do with this issue.

**Comment by Ambrevar** [comment] 2019-05-08 18:11
This should be fixed in Next 1.2.1. Feel free to re-open if you still experience the issue.

**Closed by Ambrevar** 2019-05-08 18:11 UTC

**Comment by Dav1d23** [comment] 2019-05-09 09:40
I tested this morning on my Ubuntu installation and it looks working, I'll let you know if It works on Arch as well asap.

(small note: I have issues in youtube playback on Ubuntu - the video is greenish -, it is already reported?)

Thanks!

**Comment by Ambrevar** [comment] 2019-05-09 10:59
Thanks for the feedback!

About the video: can you test with another webkitgtk browser like GNOME
Web (epiphany)?  This is probably a problem with you distribution / hardware.

**Comment by Dav1d23** [comment] 2019-05-10 09:18
I checked right now, and while not smooth as with Firefox, it is definitely working (video playback works just fine with no green artifacts, the volume button is "shaky" but still working).

May I help in any other way?

**Comment by Ambrevar** [comment] 2019-05-10 09:36
Hi!  Thanks for the feedback!
I'm glad to hear it's working now :)

Could you detail what is not as "smooth as with Firefox"?  We can try
fixing that :)

> May I help in any other way?

Sure! :)  What are you interested in?  Enhanced bookmarks, privacy / Tor
support, image blocking, ...

Do you know Common Lisp? :)

**Comment by Dav1d23** [comment] 2019-05-10 09:45
Does "I use emacs" count? ;p

I did some introduction to lisp, but no, not good.
But I'm willing to learn, do you have a place where to start?

Cheers.

**Comment by Ambrevar** [comment] 2019-05-10 10:00
"I use Emacs" does count!
Emacs Lisp is grammatically and syntactically very close to Common Lisp,
so if you can read/write ELisp you are already a good way in :)

I think two good starting points would be:

- Practical Common Lisp, a book available for free here:
http://www.gigamonkeys.com/book/.

- The cookbook: https://lispcookbook.github.io/cl-cookbook/
