### ISSUE TITLE
Titles go out-of-sync when navigating buffer history

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#434] opened 2019-10-03 10:21 UTC
**Describe the bug**

Navigate backwards shows a list of previous pages, but not actually the page I was on before.

**Precise recipe to reproduce the issue**

This happens frequently github. After clicking around issues etc. C-b would just show me a list of non-github previous pages.

Is there a chance that github is managing the `window.History` directly and Next is not catching on those changes? Otherwise, the history I see corresponds to a fully different tab (I am navigating github but my first navigate-backwards option is on a different site/domain.

**Information**
- OS name+version: OpenSUSE 15.1
- Kernel name+version: 4.12.14-lp151.28.13-default
- Desktop environment / Window manager name+version: i3 4.15
- Next version (from =M-x next-version= or =next --version=): Next 1.3.2-16f2381
- How you installed Next (Guix pack, package manager, build from source): built from source
- SBCL version (if built from source): 1.5.4-lp151.100.1-suse
- WebKitGTK+ / PyQt-Webengine version: webkit2gtk: 2.24.2-lp151.2.3.1

**Comment by Ambrevar** [comment] 2019-10-03 10:43
Indeed, I noticed similar problem.  The thing is that sometimes GitHub
entries get added to history, sometimes not.  I'd like to understand
what's going on exactly.  Would you have precise recipes to reproduce
those 2 cases?

Maybe we should save the history when WebKitGTK hits
"WEBKIT_LOAD_COMMITTED" and not just on "WEBKIT_LOAD_FINISHED".

**Comment by hsanjuan** [comment] 2019-10-03 10:50
I don't have a clear recipe to reproduce, but I have an open window with a tab suffering this problem, so if there's anything I can do to debug... Actually "switch-to-buffer" refers to that tab as if it was in a different page than it actually is.

**Comment by Ambrevar** [comment] 2019-10-03 11:15
You mean the URL / title of the buffer is incorrect?

This is possible if the loading did not complete properly.

**Comment by hsanjuan** [comment] 2019-10-03 11:27
> You mean the URL / title of the buffer is incorrect? This is possible if the loading did not complete properly.

Actually, url seems fine, the title seems outdated though.

**Comment by jmercouris** [comment] 2019-10-03 13:47
Could be some Javascript SPA (single page application), perhaps we should look at other browsers and see for which signals they recognize a page load? Epiphany seems a good candidate.

**Comment by Ambrevar** [comment] 2019-10-04 15:27
I've fixed the GitHub issue on master.

Regarding the title issue: I can't reproduce reliably, so it's hard to
fix until we've found a clear recipe.

**Comment by jmercouris** [comment] 2019-10-04 15:33
What was the issue with GitHub? Did you just listen for a different signal?

**Comment by Ambrevar** [comment] 2019-10-04 16:03
In the original fix, I used the did-commit-navigation signal when the
URI changed.

Later, I moved the history function to did-finish-navigation.

So now I updated the URI change to use did-finish-navigation.

**Comment by jmercouris** [comment] 2019-10-04 16:04
I've seen your commit and made a comment. If the URL does not change, having duplicate signals should not be a problem when adding to the tree, as it will not create a new node if the new URL is not distinct.

**Comment by Ambrevar** [comment] 2020-04-09 08:53
Should be fixed with 5911fa56883556896f1548abe7dec264c9f0a7b9.

**Closed** 2020-04-10 13:53 UTC
Labels: 2.0
