### ISSUE TITLE
Open link in a new buffer instead of spawning a  new window.

### ISSUE THREAD

**Issue by alexanderbarbosa** [atlas-engineer/next#311] opened 2019-08-12 11:28 UTC
Hi,

Its kinda annoying that some links force browsers to open a new window.

Some links are still unacessible by Next links hints, so we have to mice click those.

But it behaves in a rather weird way:

Next  spawns a new window with the same collection of buffers, and users have to close that other instance of Next, AFTER killing the buffer that forced to open that new window.

Reproducing:

- Clicking cnn.com random link, opens a new page and a new instance of Next.
- Kill that page but Next still has two instance open
- Kill that other instance

Thanks!

---
Debian 10 SID
Next: Upstream

**Comment by Ambrevar** [comment] 2019-08-16 13:41
All Next windows have the list of all buffers.  Killing a window does not kill a buffer, this is a feature, not a bug :)

In the future, we could filter buffers by windows, still got to think this through though.

Regarding the title of the issue: you are right, we should let the user choose whether they want to open in a new buffer or new window.  Simple fix :)
Would you be interested in working on a pull request?  This is a great opportunity for an introduction to hacking Next ;)
I can guide you through the process if you need help, no problem!

**Comment by Ambrevar** [comment] 2019-08-21 11:04
Fixed in 00e904b6cd341df39160e37fe22152cc69f624e6.

**Closed** 2019-08-21 17:57 UTC
