### ISSUE TITLE
C-g does not work on all websites

### ISSUE THREAD

**Issue by hsanjuan** [atlas-engineer/next#648] opened 2020-04-11 20:30 UTC
**Describe the bug**

Hitting C-g on https://www.triodos.de/banking crashes Next

**Precise recipe to reproduce the issue**

**Information**
- OS name+version: OpenSUSE Tumbleweed
- Desktop environment / Window manager name+version: i3
- Next version (from =M-x next-version= or =next --version=): ae42dfbf797a6e2de48deef9e074dce8917e5631
- How you installed Next (Guix pack, package manager, build from source): source
- Lisp implementation/version (if built from source):
- WebKitGTK+ | QtWebEngine version: Gtk 2.28

**Output when started from a shell**

```
Unhandled TYPE-ERROR in thread #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING
                                  {100726A423}>:
  The value
    NIL
  is not of type
    STRING
  when binding STRING

Backtrace for: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {100726A423}>
0: (MAKE-STRING-INPUT-STREAM NIL 69852486959200 (#S(CFFI:CALLBACK :ID 232 :WEB-VIEW #<CL-WEBKIT2:WEBKIT-WEB-VIEW {1005D801E3}> :FUNCTION #<CLOSURE (LAMBDA (NEXT::ELEMENTS-JSON) :IN NEXT::QUERY-HINTS) {1008546D7B}>))) [external]
1: (JSON:DECODE-JSON-FROM-STRING NIL)
2: (NEXT::ELEMENTS-FROM-JSON NIL)
3: ((LAMBDA (NEXT::ELEMENTS-JSON) :IN NEXT::QUERY-HINTS) NIL)
4: ((LAMBDA (CL-WEBKIT2::SOURCE-OBJECT CL-WEBKIT2::RESULT CL-WEBKIT2::USER-DATA) :IN "/home/hector/common-lisp/cl-webkit/webkit2/webkit2.web-view.lisp") #<unused argument> #.(SB-SYS:INT-SAP #X7F0F84228600) #.(SB-SYS:INT-SAP #X000000E8))
5: ((LAMBDA (SB-ALIEN::ARGS-POINTER SB-ALIEN::RESULT-POINTER FUNCTION) :IN "/home/hector/common-lisp/next/quicklisp/dists/quicklisp/software/cl-cffi-gtk-20190710-git/gdk/gdk.seat.lisp") #<unavailable argument> #<unavailable argument> #<unavailable argument>)
6: ("foreign function: funcall_alien_callback")
7: ("foreign function: callback_wrapper_trampoline")
8: ("foreign function: #x50101F4C")
9: ((LAMBDA NIL :IN GTK:ENSURE-GTK-MAIN))
10: ((LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS))
11: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
12: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
13: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
14: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
15: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {7F0F9957ED7B}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {100726A423}>> NIL T NIL)
16: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "cl-cffi-gtk main thread" RUNNING {100726A423}> NIL #<CLOSURE (LAMBDA NIL :IN BORDEAUX-THREADS::BINDING-DEFAULT-SPECIALS) {100726A3CB}> NIL)
17: ("foreign function: call_into_lisp")
18: ("foreign function: new_thread_trampoline")
```

**Comment by jmercouris** [comment] 2020-04-11 22:19
Thank you for the report! I know why this is, there is something about that specific web page causing the JS in the link hints to fail and return NIL, we could more gracefully handle this failure on the Lisp side, and work on the parenscript as well to make link hints more reliable

**Comment by Ambrevar** [comment] 2020-04-12 08:08
I think instead when not running from the REPL, we should add a
`handler-case` around the parenscript callback to ensure that we don't
needlessly hang the browser on Javascript errors.  After all, Javascript
errors should only be problematic for the current buffer, not the whole program.

**Comment by jmercouris** [comment] 2020-04-13 09:40
I agree with that! I was just thinking it would be so nice if the debugger could show up in a running binary without needing an attached terminal

**Comment by jmercouris** [comment] 2020-04-13 09:40
With the user able to select the restarts as well, of course

**Comment by Ambrevar** [comment] 2020-04-13 11:02
We will be able to do this once we have an integrated REPL, I suppose.
Probably post-2.0 though, so I'd say let's just handle the condition for
now, it's more important to have a non-hanging Next for 2.0!

**Comment by jmercouris** [comment] 2020-04-13 11:35
Indeed, one step at a time :-)

**Comment by hsanjuan** [comment] 2020-04-13 12:55
Having the full browser crash is a show-stopper to make `Next` my day-to-day default browser, so ideally it should never die like this.

But also don't forget to make the js in the link hints not crash. Link hints should work, specially in simple website like this (even if it's broken below).

**Comment by Ambrevar** [comment] 2020-04-13 14:21
Fixed in 3911fd78f50ac60275f32ed7e402dc65a89fb4f2.
You'll need to update cl-webkit first.

Javascript should never hang Next from now on! :)

@jmercouris: The issue was that error handling was done in the CFFI
callback on which we have no control.  So there was no way to tell
"ignore errors" from Next.

I've changed the design a little bit: We can now pass an error handler
to cl-webkit.  We can do whatever we want from the handler.
For now, we just display the javascript error (which really works this
time, unlike before).

Later, we can add parenscript-specific error handling.  Since we don't
need it for now, let's worry about it later.

**Comment by Ambrevar** [comment] 2020-04-13 14:22
By the way, the element-hint error on the triodos page is

--8<---------------cut here---------------start------------->8---
Message: https://www.triodos.de/banking:20:27: TypeError: null is not an object (evaluating 'styleElement.sheet.insertRule')
--8<---------------cut here---------------end--------------->8---

**Comment by jmercouris** [comment] 2020-04-13 14:26
Great! Thank you! We will hopefully make it better at handling errors in the future :-)

**Comment by jmercouris** [comment] 2020-04-13 14:27
Maybe our parenscript macro should include an optional error-handling body or something? (instead of a separate function)?

**Comment by Ambrevar** [comment] 2020-04-13 14:31
> Maybe our parenscript macro should include an optional error-handling body or something? (instead of a separate function)?

Exactly, we could do that.  Let's keep that on our minds when the time
comes to handler Javascript errors.

**Comment by hsanjuan** [comment] 2020-04-13 21:17
Have you thought of adding cl-webit as a git submodule so that you can actually keep things aligned?

**Comment by Ambrevar** [comment] 2020-04-14 06:47
> Have you thought of adding cl-webkit as a git submodule so that you can actually keep things aligned?

Probably a good idea indeed!
We'd need to make some adjustments to the Makefile, since the submodules
path is not found by ASDF by default.

**Comment by jmercouris** [comment] 2020-04-14 08:08
While it does seem a good idea, we would end up adding a lot of repositories as submodules. Let’s please keep them separate, it is a library that a variant of Next depends upon, rather than a companion/necessary library. Is that OK?

**Comment by Ambrevar** [comment] 2020-04-14 08:19
Submodules are just a convenient way to load external Gits.
They won't be part of Next.

For now we only need cl-webkit.

Our Makefile already does some `git clone` juggling to get cl-webkit in
case it's not found.  We could replace this manual trick with Git
submodules which do the same thing more cleanly.

**Comment by jmercouris** [comment] 2020-04-14 08:23
I've had bad experiences in the past with submodules. Especially when users don't use the correct command to pull the submodules as well. They are separate programs, and a dependent library is not really the best use case for a submodule, especially when QL exists. I really think we should avoid them. Should we use them, maybe in the libraries folder?

**Comment by Ambrevar** [comment] 2020-04-14 08:55
To clarify, submodules are optional.

In the makefile, we would implement the following logic:

Does (asdf:load-system :cl-webkit) work?
- If yes, then build as usual.
- If not, then `git ubmodules ...` then build as usual.

The point is to replace the hack I had put in place with `git clone ...cl-webkit`.

> They are separate programs, and a dependent library is not really the
> best use case for a submodule, especially when QL exists.

But the problem here is that cl-webkit is a moving target and QL does
not do the job for a whole month until the next update.

> I really think we should avoid them. Should we use them, maybe in the libraries folder?

What do you mean? Store the submodule in the "libraries" folder?  No
problem, we can store submodules anywhere.

**Comment by hsanjuan** [comment] 2020-04-14 22:12
> Especially when users don't use the correct command to pull the submodules as well

My suggestions comes from forgetting to pull cl-webkit and getting a crash when starting `next` and trying to do something.

Ideally, if I need to debug a regression and try to figure out when some problem started happening on next, reverting to a previous commit would allow me to rebuild how the project was back there, including what dependencies it was supposed to be using, in particular which commit in cl-webkit. With submodules that link exists. Currently it's a big "?".

Granted, there are other ways of resolving this than submodules (keeping the reference in your Makefile and checking that out after cloning etc), but submodules is a bit more standard to resolve particularly this.

**Comment by jmercouris** [comment] 2020-04-17 09:36
I'll be taking a look at this today and see if I can improve the link-hinting performance a little bit at the same time

**Comment by jmercouris** [comment] 2020-04-17 11:59
About this specific site:

"Refused to apply a stylesheet because its hash, its nonce, or 'unsafe-inline' does not appear in the style-src directive of the Content Security Policy."

I think this is an exception for which it will not work... anyways link hints are WAY faster now, going to work on making them lazy load non-visible hints in the background

**Comment by jmercouris** [comment] 2020-04-17 12:12
to expand upon details for this site, more or less I don't want to work around this. should sites not want injected stylesheets, then it is important to respect that, so I guess we will have to live with secure sites being broken :-D

**Comment by Ambrevar** [comment] 2020-04-17 12:41
There might be a way around it though since qutebrowser can do it.

**Comment by jmercouris** [comment] 2020-04-17 13:11
There is, it involves using renderer specific style sheets. This however would require very significant changes to the codebase

**Comment by hsanjuan** [comment] 2020-04-17 14:27
I guess it's ok as long as it doesn't crash. Can we have a warning with a message in the minibuffer when this happens though? `Sorry: CSP policy for this website blocks link hinting`

**Comment by Ambrevar** [comment] 2020-04-17 14:29
@hsanjuan

> Ideally, if I need to debug a regression and try to figure out when
> some problem started happening on next, reverting to a previous commit
> would allow me to rebuild how the project was back there, including
> what dependencies it was supposed to be using, in particular which
> commit in cl-webkit. With submodules that link exists. Currently it's
> a big "?".
>
> Granted, there are other ways of resolving this than submodules
> (keeping the reference in your Makefile and checking that out after
> cloning etc), but submodules is a bit more standard to resolve
> particularly this.

I've opened https://github.com/atlas-engineer/next/issues/670

Note that while the points you are making are important and I believe
submodules are practical, they only help that much with reproducibility.
Indeed, much of the Common Lisp libraries are fetched via Quicklisp and
we have no idea which versions the users have on their machine.

The only good way we have to reproduce issues is the
`build-scripts/guix.scm` file.  This is pretty robust since we only need
the following info to get excellent reproducibility:

- If building from source, we need the Guix commit and the Next commit.
- If installing from Guix, we only need the Guix commit.

**Comment by Ambrevar** [comment] 2020-04-18 09:00
The echo-status branch shows a Javascript error.  Maybe not very
user-friendly.

@jmercouris: Running follow-hint a second time works, although it does
not display the hints in the buffer.

I suggest we do the following:

- Print an warning in the echo area as suggested by Héctor.
- By-pass the Javascript error and make sure follow-hint works the first
  time, even if the hints don't display.

**Comment by jmercouris** [comment] 2020-04-18 09:41
We cannot easily bypass the JS error, JS execution halts upon error... what we can do is see if we can set the style sheet to be applied by the renderer rather than JS, if this is possible in QtWebEngine as well, then we can do it

**Comment by Ambrevar** [comment] 2020-04-18 09:52
Can't we catch exceptions in JavaScript?

**Comment by jmercouris** [comment] 2020-04-23 14:02
I've added exception handling to the function which adds the style sheet. Follow hint works, and the hints display, they just aren't styled (since they can't be, at least with that method)

I think that is sufficient for now. Printing something in the echo area would mean changing how parenscript is processed in the whole system to get multiple return values (the result of the link hints, as well as any messages).

**Closed by jmercouris** 2020-04-23 14:02 UTC
Labels: 2.0
